#!/usr/bin/env bash

# This script will generate a manifest for the references in the given reference dir tree
# It labels their ID as the species in the dir structure, though this may not be appropriate
# Redirect stdout to file if needed

indir="${1}"  # The root directory of a reference dir tree (as generated by download_references.sh)

species_dirs=(${indir}/*)

# Header
echo "ID,assembly"

# Rows in manifest
for species_dir in "${species_dirs[@]}"; do
  species=$(basename "${species_dir}")
  species_assemblies=(${species_dir}/*/*.fna)
  for assembly in "${species_assemblies[@]}"; do
    if [ -s "${assembly}" ]; then
      echo "${species},$(realpath ${assembly})"
    fi
  done
done

